<?php

return [
    'regions' => [
        'Northeast' => ['CT', 'DE', 'ME', 'MD', 'MA', 'NH', 'NJ', 'NY', 'PA', 'RI', 'VT'],
        'Southeast' => ['AL', 'AR', 'FL', 'GA', 'KY', 'LA', 'MS', 'NC', 'SC', 'TN', 'VA', 'WV'],
        'Midwest'   => ['IL', 'IN', 'IA', 'KS', 'MI', 'MN', 'MO', 'NE', 'ND', 'OH', 'SD', 'WI'],
        'Southwest' => ['AZ', 'NM', 'OK', 'TX'],
        'West'      => ['CO', 'ID', 'MT', 'NV', 'UT', 'WY'],
        'Pacific'   => ['AK', 'CA', 'HI', 'OR', 'WA'],
    ],

    'list' => [
        ['name' => 'Alabama',        'abbr' => 'AL', 'slug' => 'alabama',        'region' => 'Southeast'],
        ['name' => 'Alaska',         'abbr' => 'AK', 'slug' => 'alaska',         'region' => 'Pacific'],
        ['name' => 'Arizona',        'abbr' => 'AZ', 'slug' => 'arizona',        'region' => 'Southwest'],
        ['name' => 'Arkansas',       'abbr' => 'AR', 'slug' => 'arkansas',       'region' => 'Southeast'],
        ['name' => 'California',     'abbr' => 'CA', 'slug' => 'california',     'region' => 'Pacific'],
        ['name' => 'Colorado',       'abbr' => 'CO', 'slug' => 'colorado',       'region' => 'West'],
        ['name' => 'Connecticut',    'abbr' => 'CT', 'slug' => 'connecticut',    'region' => 'Northeast'],
        ['name' => 'Delaware',       'abbr' => 'DE', 'slug' => 'delaware',       'region' => 'Northeast'],
        ['name' => 'Florida',        'abbr' => 'FL', 'slug' => 'florida',        'region' => 'Southeast'],
        ['name' => 'Georgia',        'abbr' => 'GA', 'slug' => 'georgia',        'region' => 'Southeast'],
        ['name' => 'Hawaii',         'abbr' => 'HI', 'slug' => 'hawaii',         'region' => 'Pacific'],
        ['name' => 'Idaho',          'abbr' => 'ID', 'slug' => 'idaho',          'region' => 'West'],
        ['name' => 'Illinois',       'abbr' => 'IL', 'slug' => 'illinois',       'region' => 'Midwest'],
        ['name' => 'Indiana',        'abbr' => 'IN', 'slug' => 'indiana',        'region' => 'Midwest'],
        ['name' => 'Iowa',           'abbr' => 'IA', 'slug' => 'iowa',           'region' => 'Midwest'],
        ['name' => 'Kansas',         'abbr' => 'KS', 'slug' => 'kansas',         'region' => 'Midwest'],
        ['name' => 'Kentucky',       'abbr' => 'KY', 'slug' => 'kentucky',       'region' => 'Southeast'],
        ['name' => 'Louisiana',      'abbr' => 'LA', 'slug' => 'louisiana',      'region' => 'Southeast'],
        ['name' => 'Maine',          'abbr' => 'ME', 'slug' => 'maine',          'region' => 'Northeast'],
        ['name' => 'Maryland',       'abbr' => 'MD', 'slug' => 'maryland',       'region' => 'Northeast'],
        ['name' => 'Massachusetts',  'abbr' => 'MA', 'slug' => 'massachusetts',  'region' => 'Northeast'],
        ['name' => 'Michigan',       'abbr' => 'MI', 'slug' => 'michigan',       'region' => 'Midwest'],
        ['name' => 'Minnesota',      'abbr' => 'MN', 'slug' => 'minnesota',      'region' => 'Midwest'],
        ['name' => 'Mississippi',    'abbr' => 'MS', 'slug' => 'mississippi',    'region' => 'Southeast'],
        ['name' => 'Missouri',       'abbr' => 'MO', 'slug' => 'missouri',       'region' => 'Midwest'],
        ['name' => 'Montana',        'abbr' => 'MT', 'slug' => 'montana',        'region' => 'West'],
        ['name' => 'Nebraska',       'abbr' => 'NE', 'slug' => 'nebraska',       'region' => 'Midwest'],
        ['name' => 'Nevada',         'abbr' => 'NV', 'slug' => 'nevada',         'region' => 'West'],
        ['name' => 'New Hampshire',  'abbr' => 'NH', 'slug' => 'new-hampshire',  'region' => 'Northeast'],
        ['name' => 'New Jersey',     'abbr' => 'NJ', 'slug' => 'new-jersey',     'region' => 'Northeast'],
        ['name' => 'New Mexico',     'abbr' => 'NM', 'slug' => 'new-mexico',     'region' => 'Southwest'],
        ['name' => 'New York',       'abbr' => 'NY', 'slug' => 'new-york',       'region' => 'Northeast'],
        ['name' => 'North Carolina', 'abbr' => 'NC', 'slug' => 'north-carolina', 'region' => 'Southeast'],
        ['name' => 'North Dakota',   'abbr' => 'ND', 'slug' => 'north-dakota',   'region' => 'Midwest'],
        ['name' => 'Ohio',           'abbr' => 'OH', 'slug' => 'ohio',           'region' => 'Midwest'],
        ['name' => 'Oklahoma',       'abbr' => 'OK', 'slug' => 'oklahoma',       'region' => 'Southwest'],
        ['name' => 'Oregon',         'abbr' => 'OR', 'slug' => 'oregon',         'region' => 'Pacific'],
        ['name' => 'Pennsylvania',   'abbr' => 'PA', 'slug' => 'pennsylvania',   'region' => 'Northeast'],
        ['name' => 'Rhode Island',   'abbr' => 'RI', 'slug' => 'rhode-island',   'region' => 'Northeast'],
        ['name' => 'South Carolina', 'abbr' => 'SC', 'slug' => 'south-carolina', 'region' => 'Southeast'],
        ['name' => 'South Dakota',   'abbr' => 'SD', 'slug' => 'south-dakota',   'region' => 'Midwest'],
        ['name' => 'Tennessee',      'abbr' => 'TN', 'slug' => 'tennessee',      'region' => 'Southeast'],
        ['name' => 'Texas',          'abbr' => 'TX', 'slug' => 'texas',          'region' => 'Southwest'],
        ['name' => 'Utah',           'abbr' => 'UT', 'slug' => 'utah',           'region' => 'West'],
        ['name' => 'Vermont',        'abbr' => 'VT', 'slug' => 'vermont',        'region' => 'Northeast'],
        ['name' => 'Virginia',       'abbr' => 'VA', 'slug' => 'virginia',       'region' => 'Southeast'],
        ['name' => 'Washington',     'abbr' => 'WA', 'slug' => 'washington',     'region' => 'Pacific'],
        ['name' => 'West Virginia',  'abbr' => 'WV', 'slug' => 'west-virginia',  'region' => 'Southeast'],
        ['name' => 'Wisconsin',      'abbr' => 'WI', 'slug' => 'wisconsin',      'region' => 'Midwest'],
        ['name' => 'Wyoming',        'abbr' => 'WY', 'slug' => 'wyoming',        'region' => 'West'],
    ],
];
